plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

version = "${mod_loader}-${minecraft_version}-${mod_version}"
group = mod_group_id

base {
	archivesName = mod_id
}

repositories {
	mavenLocal()
	maven { url "https://cursemaven.com" }
	maven { url "https://api.modrinth.com/maven" }

	//LambDynamicLights
	maven { url "https://maven.gegy.dev" }

	//WispForest (owo-lib, endec)
	maven { url "https://maven.wispforest.io/releases" }
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

loom {
	accessWidenerPath = file("src/main/resources/travelersbackpack.accesswidener")
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"

	implementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"

	//REQUIRED
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	//Forge Config Api Port
	implementation("maven.modrinth:forge-config-api-port:rSd3GiG8")
	api 'com.electronwill.night-config:core:3.8.1'
	api 'com.electronwill.night-config:toml:3.8.1'

	//Cardinal Components
	//runtimeOnly("dev.onyxstudios.cardinal-components-api:cardinal-components-base:${project.cca_version}")
	//runtimeOnly("dev.onyxstudios.cardinal-components-api:cardinal-components-entity:${project.cca_version}")

	//Required for Polymorph
	//compileOnly "dev.onyxstudios.cardinal-components-api:cardinal-components-block:${project.cca_version}"

	//Cloth Config
	//compileOnly("dev.architectury:architectury-fabric:${project.architectury_version}")
	//compileOnly("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}")

	//OPTIONAL

	//LambDynamicLights
	compileOnly("dev.lambdaurora.lambdynamiclights:lambdynamiclights-api:4.12.1+26.2")
	localRuntime("dev.lambdaurora.lambdynamiclights:lambdynamiclights-runtime:4.12.1+26.2")

	//Crafting Tweaks
	compileOnly("maven.modrinth:balm:Gl7L60Mm")
	compileOnly("maven.modrinth:crafting-tweaks:L8AL817i")

	//Trash Slot
	implementation("maven.modrinth:trashslot:qIsYpFhq")
	implementation("maven.modrinth:balm:Gl7L60Mm")

	//ModMenu
	implementation("maven.modrinth:modmenu:njXb639R")

	//VinURL
	compileOnly("com.vinurl:VinURL:2.7.0+mc26.2") {
		transitive = false
	}

	//Trinkets
	implementation "maven.modrinth:trinkets-updated:kOeE0jtC"

	//Accessories
	//compileOnly("io.wispforest:accessories-fabric:${project.accessories_version}")
    //modImplementation("maven.modrinth:owo-lib:dZPuIa4j")
	//modImplementation("io.wispforest:endec:0.1.8")
	//modImplementation("io.wispforest.endec:gson:0.1.5")
	//modImplementation("io.wispforest.endec:netty:0.1.4")

	//REI
    //compileOnly("me.shedaniel:RoughlyEnoughItems-fabric:${project.rei_version}") //Not Updated

	//JEI
	implementation ("maven.modrinth:jei:WyzzzTmr")

	//Polymorph
	//compileOnly("maven.modrinth:polymorph:j4jPy88h")

	//Comforts
	//compileOnly ("maven.modrinth:comforts:vUdakIzK")

	//EMI
	//compileOnly("dev.emi:emi-fabric:${project.emi_version}")

	//Universal Graves
    compileOnly("maven.modrinth:universal-graves:BZfhXd0q")

	//Mouse Tweaks
	//compileOnly "curse.maven:mouse-tweaks-60089:5437294"

	//TAN
	//compileOnly("curse.maven:tan-246391:5715303")
	//compileOnly("curse.maven:glitchcore-955399:5483774")

	//Gravestones
	compileOnly("maven.modrinth:pneumono_gravestones:orcmjeln")
	//compileOnly("maven.modrinth:pneumono_core:Y03YVYzM")
}

processResources {
	var replaceProperties = [
			minecraft_version      : minecraft_version,
			minecraft_version_range: minecraft_version_range,
			mod_id                 : mod_id,
			mod_name               : mod_name,
			mod_display_name       : mod_display_name,
			mod_license            : mod_license,
			mod_version            : mod_version,
			mod_authors            : mod_authors,
			mod_description        : mod_description,
			mod_display_url        : mod_display_url,
			mod_issue_tracker_url  : mod_issue_tracker_url,
	]
	inputs.properties replaceProperties

	filesMatching('fabric.mod.json') {
		expand replaceProperties
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	//withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}