plugins {
	id 'fabric-loom' version '1.10-SNAPSHOT'
}

version = "${mod_loader}-${minecraft_version}-${mod_version}"
group = mod_group_id

base {
	archivesName = mod_id
}

repositories {
	maven { url "https://cursemaven.com" }
	maven { url = "https://maven.ladysnake.org/releases" }
	maven { url "https://maven.shedaniel.me/" }
	maven { url "https://maven.jamieswhiteshirt.com/libs-release" }
	maven { url "https://api.modrinth.com/maven" }
	maven { url = "https://maven.parchmentmc.org" }
    maven { url "https://maven.wispforest.io/releases" }
	maven { url "https://maven.twelveiterations.com/repository/maven-public/" }
}

fabricApi {
	configureDataGeneration()
}

loom {
	accessWidenerPath = file("src/main/resources/travelersbackpack.accesswidener")
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.layered() {
		officialMojangMappings()
		parchment("org.parchmentmc.data:parchment-1.20.1:2023.09.03@zip")
	}
	modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	//REQUIRED

	//Cardinal Components
	modImplementation "dev.onyxstudios.cardinal-components-api:cardinal-components-base:${project.cca_version}"
	modImplementation "dev.onyxstudios.cardinal-components-api:cardinal-components-entity:${project.cca_version}"

	//Cloth Config
	modRuntimeOnly("maven.modrinth:architectury-api:WbL7MStR")
	//modImplementation("maven.modrinth:cloth-config:2xQdCMyG")
	modImplementation("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}")

	//Reach Entity Attributes
	include modImplementation("com.jamieswhiteshirt:reach-entity-attributes:${project.reach_entity_attributes_version}")

	//OPTIONAL

	//Crafting Tweaks
	modCompileOnly("curse.maven:balm-fabric-500525:7087238")
	modCompileOnly("curse.maven:crafting-tweaks-fabric-233071:6784524")
	modCompileOnly("net.blay09.mods:kuma-api-fabric:[20,20.2)")

	//Trash Slot
	modCompileOnly("maven.modrinth:trashslot:Ve2pngwH")

	//ModMenu
	modImplementation("maven.modrinth:modmenu:lEkperf6")

	modCompileOnly("maven.modrinth:spice-of-life-valheim-edition:kcOOe5S6")

	//Majrusz
	//modRuntimeOnly("curse.maven:mpd-430642:5293468")
	//modRuntimeOnly("curse.maven:ml-437409:5301915")

	//Deselect
	modCompileOnly("maven.modrinth:deselect:Ter2PgA6")

    //OPAC
    modCompileOnly("maven.modrinth:forge-config-api-port:1aKtMQZE")
	modCompileOnly("maven.modrinth:open-parties-and-claims:T2Gpqmeu")

	//Stack Size Edit
	//modImplementation("maven.modrinth:stack-size-edit:Fml5ea8S")

	//Trinkets
	modImplementation("maven.modrinth:trinkets:AHxQGtuC")

	//Accessories
    modCompileOnly("maven.modrinth:accessories:A7wwzJ0e")
    modCompileOnly("maven.modrinth:accessories-tc-layer:dfzKbUiE")
    modCompileOnly("maven.modrinth:owo-lib:zyOBB7J4")
    modCompileOnly("io.wispforest:endec:0.1.8")
    modCompileOnly("io.wispforest.endec:gson:0.1.5")
    modCompileOnly("io.wispforest.endec:netty:0.1.4")
    modCompileOnly("maven.modrinth:sodium:mhZtY2lR")
    modCompileOnly("maven.modrinth:lithium:ZSNsJrPI")

	//REI
	modImplementation("maven.modrinth:rei:nYcMSS03")

	//JEI
	modCompileOnly("maven.modrinth:jei:wbPLxn0B")

	//AudioPlayer
	modCompileOnly("maven.modrinth:audioplayer:X5VnNQLt")
	modCompileOnly("maven.modrinth:simple-voice-chat:4DG7BvdF")
	modCompileOnly("maven.modrinth:admiral:0.4.5+1.20.1+fabric")

	//Comforts
	modCompileOnly("maven.modrinth:comforts:pMr60Kkq")

	//EMI
	modCompileOnly("maven.modrinth:emi:VvPw7Vi5")

	//Dehydration
	modCompileOnly("curse.maven:dehydration-410830:5204866")

	//Universal Graves
	modCompileOnly("curse.maven:universal-graves-497175:5706124")

	//Polymorph
	modCompileOnly("maven.modrinth:polymorph:z88tNWJh")

	//TAN
	modCompileOnly("curse.maven:tan-246391:5815864")

	//Carry On
	modCompileOnly("curse.maven:carryon-274259:4882498")

	//Yigd
	modCompileOnly("maven.modrinth:yigd:C2PIq5XX")
	//modCompileOnly("io.github.cottonmc:LibGui:8.1.1+1.20.1")
	//modCompileOnly("me.lucko:fabric-permissions-api:0.2-SNAPSHOT")

	//Gravestones
	modCompileOnly("maven.modrinth:pneumono_gravestones:PqDpF1hy")
	modCompileOnly("maven.modrinth:pneumono_core:MtM4xjYo")

	//Ae2
	modCompileOnly("maven.modrinth:ae2:kA3rm9EP")

	//Create
	//modRuntimeOnly "maven.modrinth:create-fabric:h2HgGyvA"
	//modRuntimeOnly "maven.modrinth:fxnt-create-storage:H3voyod7"
	//modRuntimeOnly "maven.modrinth:porting_lib:GWCykcY1"
	//modRuntimeOnly "io.github.fabricators_of_create.Porting-Lib:$module:2.3.5-beta.31+1.20.1"
	//modRuntimeOnly "maven.modrinth:forge-config-api-port:CtENDTlF"

	//modRuntimeOnly("eu.pb4:sgui:1.2.2+1.20")
	//modRuntimeOnly("eu.pb4:placeholder-api:2.1.1+1.20")
	//modRuntimeOnly('xyz.nucleoid:server-translations-api:2.0.0+1.20')
	//modRuntimeOnly('eu.pb4:polymer-core:0.5.3+1.20.1')
	//modRuntimeOnly('eu.pb4:polymer-resource-pack:0.5.3+1.20.1')
	//modRuntimeOnly('eu.pb4:polymer-virtual-entity:0.5.3+1.20.1')
	//modRuntimeOnly('eu.pb4:predicate-api:0.1.2+1.20')
	//modRuntimeOnly("eu.pb4:common-protection-api:1.0.0")
}

processResources {
	var replaceProperties = [
			minecraft_version      : minecraft_version,
			minecraft_version_range: minecraft_version_range,
			mod_id                 : mod_id,
			mod_name               : mod_name,
			mod_display_name       : mod_display_name,
			mod_license            : mod_license,
			mod_version            : mod_version,
			mod_authors            : mod_authors,
			mod_description        : mod_description,
			mod_display_url        : mod_display_url,
			mod_issue_tracker_url  : mod_issue_tracker_url,
	]
	inputs.properties replaceProperties

	filesMatching('fabric.mod.json') {
		expand replaceProperties
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}