plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.141'
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = "${mod_loader}-${minecraft_version}-${mod_version}"
group = mod_group_id

base {
    archivesName = mod_id
}

sourceSets.main.resources {
    srcDir('src/generated/resources')
    exclude("src/generated/**/.cache")
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

neoForge {
    version = project.neo_version
    validateAccessTransformers = true
    //accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg') //Auto detected

    runs {
        client {
            client()
        }
        client2 {
            client()
            programArguments = ["--username Dev2"]
        }
        data {
            //#data
            clientData()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
    maven { url "https://cursemaven.com" }
    maven { url 'https://api.modrinth.com/maven' }
}

dependencies {
    implementation("net.neoforged:neoforge:${neo_version}")

    //Curios
    compileOnly("maven.modrinth:curios:68gxflop")

    //JEI
    implementation("maven.modrinth:jei:XkrFsbih")

    //EMI
    //compileOnly("maven.modrinth:emi:ouSj7NfF") //Not Updated

    //REI
    compileOnly("maven.modrinth:rei:rCAaJej0") //Not Updated
    compileOnly("maven.modrinth:architectury-api:EvL9NK2R") //Not Updated
    compileOnly("maven.modrinth:cloth-config:Wsus0EWg") //Not Updated

    //Crafting Tweaks
    compileOnly("maven.modrinth:crafting-tweaks:Lnhol0EM")
    compileOnly("maven.modrinth:balm:4q61ySlS")

    //Trash Slot
    compileOnly("maven.modrinth:trashslot:trA79xXQ")

    //Comforts
    compileOnly("maven.modrinth:comforts:CZFrqdSy") //Not Updated

    //Accessories
    compileOnly("maven.modrinth:accessories:Lp7d65h7") //Not Updated
    compileOnly("maven.modrinth:owo-lib:U1h2fIEv") //Not Updated

    //Mouse Tweaks
    //implementation("curse.maven:mousetweaks-60089:5637846")

    //Polymorph
    //implementation("curse.maven:polymorph-388800:5696658")

    //Tough as Nails
    compileOnly("maven.modrinth:tough-as-nails:6zSGsGJC") //Not Updated
    //runtimeOnly("curse.maven:glitchcore-955399:5645390")
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_dependency_version,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_display_name       : mod_display_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
            mod_display_url        : mod_display_url,
            mod_issue_tracker_url  : mod_issue_tracker_url,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}