# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Minimum
#loader_version=0.15.11
#fabric_version=0.100.0+1.20.6

# Mod Information
mod_loader=fabric
mod_id=travelersbackpack
mod_version=10.1.34
mod_group_id=com.tiviacz.travelersbackpack
mod_name=TravelersBackpack
mod_display_name=Traveler's Backpack
mod_license=GNU LESSER GENERAL PUBLIC LICENSE
mod_authors=Tiviacz1337
mod_description=Unique and upgradeable backpacks with customization, Trinkets/Accessories integration and more!
mod_display_url=https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric
mod_issue_tracker_url=https://github.com/Tiviacz1337/Travelers-Backpack/issues

# Minecraft Version Information
minecraft_version=1.21.1
minecraft_version_range=~1.21.1

# Fabric Version Information
fabric_version=0.116.0+1.21.1
fabric_loader_version=0.16.14

# Dependencies
cca_version=6.1.0
cloth_config_version=15.0.127