# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G

# Minimum
#loader_version=0.14.0
#fabric_version=0.90.0+1.20.1

# Mod Information
mod_loader=fabric
mod_id=travelersbackpack
mod_version=9.1.51
mod_group_id=com.tiviacz.travelersbackpack
mod_name=TravelersBackpack
mod_display_name=Traveler's Backpack
mod_license=GNU LESSER GENERAL PUBLIC LICENSE
mod_authors=Tiviacz1337
mod_description=Unique and upgradeable backpacks with customization, Trinkets integration and more!
mod_display_url=https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric
mod_issue_tracker_url=https://github.com/Tiviacz1337/Travelers-Backpack/issues

# Minecraft Version Information
minecraft_version=1.20.1
minecraft_version_range=~1.20.1

# Fabric Version Information
fabric_version=0.92.5+1.20.1
fabric_loader_version=0.16.14

# Dependencies
cca_version = 5.2.2
cloth_config_version = 11.1.118
reach_entity_attributes_version = 2.4.0
