# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Mod Version Information
mod_loader=fabric
mod_id=travelersbackpack
mod_version=10.11.10
mod_group_id=com.tiviacz.travelersbackpack
mod_name=TravelersBackpack
mod_display_name=Traveler's Backpack
mod_license=GNU LESSER GENERAL PUBLIC LICENSE
mod_authors=Tiviacz1337
mod_description=Unique and upgradeable backpacks with customization, Trinkets/Accessories integration and more!
mod_display_url=https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric
mod_issue_tracker_url=https://github.com/Tiviacz1337/Travelers-Backpack/issues

# Minecraft Version Information
minecraft_version=1.21.11
minecraft_version_range=~1.21.11

# Fabric Version Information
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_version=0.140.0+1.21.11

# Dependencies
cca_version = 7.3.0
accessories_version=1.4.3-beta+1.21.10
accessories_version_old=1.0.0-beta.35+1.21
trinkets_canary_version = 3.11.0-1.21.11
emi_version = 1.1.18+1.21.1
cloth_config_version = 21.11.152
rei_version = 20.0.811
jei_version = 27.3.0.12
mod_menu_version = 17.0.0-alpha.1
architectury_version = 17.0.8