license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_display_name}"
    displayURL = "${mod_display_url}"
    issueTrackerURL = "${mod_issue_tracker_url}"
    authors = "${mod_authors}"
    description = '''${mod_description}'''
    logoFile = "assets/${mod_id}/textures/logo.png"

[[accessTransformers]]
    file = "META-INF/accesstransformer.cfg"

[[mixins]]
    config = "travelersbackpack.mixins.json"

[[dependencies.${ mod_id }]]
    modId = "neoforge"
    type = "required"
    versionRange="[${neo_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${ mod_id }]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"